services:
  - type: web
    name: lingualearn
    runtime: python
    plan: free
    buildCommand: >-
      pip install -r requirements.txt &&
      python manage.py migrate --noinput &&
      python manage.py seed_data &&
      python manage.py collectstatic --noinput
    startCommand: python -m gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: "3.13"
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
