# Generated by Django 6.0.7 on 2026-08-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['category__name', 'level']},
        ),
        migrations.AddField(
            model_name='quiz',
            name='level',
            field=models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], default='debutant', max_length=20),
        ),
    ]
